### ISSUE TITLE
pin fs, etc

### ISSUE THREAD

**Issue by djsutherland** [conda-forge/fs.sshfs-feedstock#2]
The package declares specific version dependencies for `fs` and so on: https://github.com/althonos/fs.sshfs/blob/0ce4e1eb009dcc1833c02ac6aebfe0799ea755de/setup.cfg#L35-L39. But it does it with a weird syntax I can't find in the documentation (though it's not easy to search for) `fs ~=2.0.7`. I don't know what that `~` does, so I'm not sure the right way to pin it in the conda-forge package either. :)

**Comment by ocefpaf** [comment]
See https://www.python.org/dev/peps/pep-0440/#version-specifiers

(And yeah, that is quite annoying.)

**Comment by djsutherland** [comment]
Ah, the other places I found in the `pip`/`setuptools` documentation totally did not link there. :)

**Comment by ReimarBauer** [comment]
I think we don't have the ~ syntax, added for now >= and discuss this with the author.

**Comment by djsutherland** [comment]
I think the right thing is eg `~=1.0.7` should be `==1.0.*,>=1.0.7`.

**Comment by althonos** [comment]
The actual dependencies are (in conda-friendly format):
```yml
run:
- six >=1.10.0, <2
- paramiko >= 2, <3
- fs >= 2.0.7, <2.1
- configparser [py2k]
```

The weird thing about `fs < 2.1` is because `fs 2` is a new codebase, so Will increases the bugfix specifier for any change that is not backwards compatible, and the minor release specifier for any change that is backwards incompatible, never modifying the major release specifier. So `fs==2.1` may break compatibility.

No need to pin configparser though, since it is a backport that does not use semantic versioning, but ensures complete backward compatibility.

**Comment by djsutherland** [comment]
Thanks @althonos!

@ReimarBauer, the conda-forge preferred formatting of this would be:

```yaml
  run:
    - six >=1.10.0,<2
    - paramiko >=2,<3
    - fs >= 2.0.7,<2.1
    - configparser  # [py2k]
```

**Comment by ocefpaf** [comment]
BTW I think I saw a PR to conda some time ago that added the `~=` syntax. Not sure if it was on the conda-skeleton parser or something general. Maybe @msarahan knows better. If that exist we can start using it, even though I really don't like it :stuck_out_tongue_winking_eye:

aside: I don't like that syntax b/c my biased interpretation is to read it as **not this version number**.

**Comment by ReimarBauer** [comment]
ok, i fix it. my mistake
